CREATE TABLE SERVIDOR(
	ID_SERVIDOR INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	NOMESERVIDOR VARCHAR(50) NOT NULL,
	MAT VARCHAR(50) NOT NULL,
	CARGO VARCHAR(50) NOT NULL,
	RG VARCHAR(50) NOT NULL,
	CPF VARCHAR(50) NOT NULL,
	LOT VARCHAR(50) NOT NULL,
);


CREATE TABLE DIARIA(
	ID_DIARIA INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	ID_SERVIDOR INT NOT NULL,
	SAIDA VARCHAR(50) NOT NULL,
	HORAS VARCHAR(50) NOT NULL,
	DESTINO VARCHAR(50) NOT NULL,
	HORAD VARCHAR(50) NOT NULL,
	TIPO VARCHAR(50) NOT NULL,
	OBJ VARCHAR(50) NOT NULL,

	FOREIGN KEY (ID_SERVIDOR) REFERENCES SERVIDOR (ID_SERVIDOR)
);


CREATE TABLE CBANCARIA(
	ID_CBANCARIA INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
	ID_SERVIDOR INT NOT NULL,
	BANCO VARCHAR(50) NOT NULL,
	AGEN VARCHAR(50) NOT NULL,
	CONTA VARCHAR(50) NOT NULL,

	FOREIGN KEY (ID_SERVIDOR) REFERENCES SERVIDOR (ID_SERVIDOR)
);