CREATE PROCEDURE spDelServidor
	
	@NOMESERVIDOR VARCHAR(50),
	@MAT INT

AS
BEGIN

	SELECT @MAT = MAT FROM SERVIDOR WHERE NOMESERVIDOR = @NOMESERVIDOR OR MAT = @MAT
	DELETE FROM SERVIDOR WHERE MAT = @MAT

END