CREATE PROCEDURE spEditServidor

	@NOMESERVIDOR VARCHAR(50),
	@MAT INT,
	@CARGO VARCHAR(50),
	@LOT VARCHAR(50)

AS
BEGIN
	
	DECLARE @MAT2 INT = 0
	SELECT @MAT2 = MAT FROM SERVIDOR WHERE NOMESERVIDOR = @NOMESERVIDOR OR MAT = @MAT
	UPDATE SERVIDOR SET NOMESERVIDOR = @NOMESERVIDOR, MAT = @MAT, CARGO = @CARGO, LOT = @LOT WHERE MAT = @MAT2

END